BlobToBlobConverterJob:
    LogsConnString:
        settings-key: BlobToBlobConverterJob-LogsConnString
        types:
            - AzureTableStorage
    InputBlobConnString:
        settings-key: BlobToBlobConverterJob-InputBlobConnString
        types:
            - AzureTableStorage
    OutputBlobConnString:
        settings-key: BlobToBlobConverterJob-OutputBlobConnString
        types:
            - AzureTableStorage
    InputContainer:
        settings-key: BlobToBlobConverterJob-InputContainer
    BlobScanPeriod:
        settings-key: BlobToBlobConverterJob-BlobScanPeriod
    ProcessingType:
        settings-key: BlobToBlobConverterJob-ProcessingType
    MessageMode:
        settings-key: BlobToBlobConverterJob-MessageMode
    NugetPackage:
        settings-key: BlobToBlobConverterJob-NugetPackage
    ExcludedPropertiesMap:
        settings-key: BlobToBlobConverterJob-ExcludedPropertiesMap
        types:
            - Json
    IdPropertiesMap:
        settings-key: BlobToBlobConverterJob-IdPropertiesMap
        types:
            - Json

MonitoringServiceClient:
    MonitoringServiceUrl:
        settings-key: MonitoringServiceUrl       

SlackNotifications:
    AzureQueue:
        ConnectionString:
            settings-key: SlackNotificationsConnString
            types:
                - AzureTableStorage
        QueueName: 
            settings-key: SlackQueueName